name: Workflow Using Configuration variables||| Github Action
run-name: Created by ${{ github.actor }}
on:
  workflow_dispatch: 
env: 
  Cloud: Azure Cloud
jobs:
  First_Job:
    name: My First Job 
    runs-on: ubuntu-latest
    env: 
      Greeting: Hello 
    steps:
      - name: My First Step
        run: echo "$Greeting $User is using $Cloud to build Infra
        env:
          User: Sunil
